### PR TITLE
[SYCL] Updates

### PR DESCRIPTION
**Pull request by abagusetty**
1. Removes dependency of DPCT
2. Simplifies sycl::queue creation and usage
3. Added SYCL experimental portability
4. Fixed issues with SYCL 2020 compatibility and several warnings

### CODE REVIEW

**Comment by victor-anisimov** [comment]
Thank you for the great work, Abhishek! The cmake build looks good. However, your Makefile.sycl is not up-to-date with the rest of your changes. Try "make sycl" from the root directory Librett.

**Comment by victor-anisimov** [comment]
Another observatiion is that file dpcpprocm_toolchain.cmake is not in the right place. How about moving it under cmake/toolchains?

**Comment by abagusetty** [comment]
> Thank you for the great work, Abhishek! The cmake build looks good. However, your Makefile.sycl is not up-to-date with the rest of your changes. Try "make sycl" from the root directory Librett.

@victor-anisimov @ajaypanyala Thanks for taking a peek. I was just wondering if I missed something. Tried running `make sycl` from the root directory and get this:
With CMake present, does one need the makefile.* too ?

```bash
icpx -c -Isrc -std=c++17  -O3 -fPIC -DSYCL -fsycl -fsycl-targets=spir64_gen -Xsycl-target-backend "-device 12.60.7" -march=native  -o build/GpuModel.o src/GpuModel.cpp
icpx: warning: argument unused during compilation: '-Xsycl-target-backend -device 12.60.7' [-Wunused-command-line-argument]
make[1]: *** No rule to make target 'build/GpuMem.o', needed by 'lib/librett.a'.  Stop.
make[1]: Leaving directory '/home/abagusetty/nwx/Librett'
make: *** [Makefile:17: sycl] Error 2
```

**Comment by victor-anisimov** [comment]
@abagusetty Could you similarly remove build/GpuMem.o from Makefile.cuda and Makefile.hip to address the changes in file names. This is presumably the last change to make the PR fully functional.

**Pull request merged**
